# Generated by Django 4.0.3 on 2022-04-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('key_carrinho', models.CharField(db_index=True, max_length=40, verbose_name='Chave do carrinho')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('total_por_item', models.DecimalField(decimal_places=4, max_digits=15)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Item do',
                'verbose_name_plural': 'Itens dos carrinhos',
                'db_table': 'item_carrinho',
                'unique_together': {('key_carrinho', 'produto')},
            },
        ),
    ]
