# Generated by Django 4.0.3 on 2022-04-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geral', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('desconto_total', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_bruto', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_frete', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('total_por_item', models.DecimalField(decimal_places=4, max_digits=15)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens das vendas',
                'db_table': 'item_venda',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geral.cidade', verbose_name='Cidade')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entregas',
            },
        ),
    ]
