# Generated by Django 4.0.3 on 2022-04-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='url',
            new_name='slug',
        ),
    ]
