# Generated by Django 4.0.3 on 2022-04-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_url_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='url',
            new_name='slug',
        ),
    ]
